#pragma once

#define WIFI_SSID     "<WiFi-SSID>"
#define WIFI_PASSWORD "<WiFi-PASSWORD>"
#define MQTT_USER     "<MQTT-USERNAME>"
#define MQTT_PASSWORD "<MQTT-PASSWORD>"
#define MQTT_SERVER   "<MQTT-SERVER-IP>"
#define OTA_PASSWORD  "<OTA-PASSWORD>"

#define IWIDTH  240
#define IHEIGHT 240
#define BACKGROUND TFT_BLACK
#define CLOCK_BG TFT_BLUE // TFT_DARKCYAN
#define TEXT_COLOUR TFT_YELLOW
#define MSG_BUFFER_SIZE	(50)
#define DEG2RAD 0.0174532925